version: "3.9"
services:
  lightspeed_1:
    container_name: lightspeed_1
    image: lightspeed_1
    build: .
    volumes:
      - ./ip_addresses.txt:/app/ip_addresses.txt # Specify location of the file with IPs list
      - ./perfmon.csv:/app/perfmon.csv # Collected performance stats
    environment:
      - IPS_FILE=/app/ip_addresses.txt
